language: python
python:
  - "2.6"
  - "2.7"
install:
  # Self-install for setup.py-driven deps
  - pip install -e .
  # Dev (doc/test running) requirements
  - pip install coveralls # For coveralls.io specifically
  - pip install -r dev-requirements.txt
script:
  # Main tests, with coverage!
  - coverage run --source=paramiko test.py --verbose
  # Ensure documentation & invoke pipeline run OK
  - invoke www
  - invoke docs
notifications:
  irc:
    channels: "irc.freenode.org#paramiko"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false
after_success:
  - coveralls
